# Site settings
title: Komal Ilyas Profile
description: Komal Ilyas profile
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Komal Ilyas
user_description: I am currently working as a manufacturing engineer at Integrated Dynamic Electron Solutions Pleasanton, CA. I am pursuing masters in computer engineering from Texas A&M University, College station,TX. My areas of expertise include machine learning workflow, image segmentation, deep learning, cost optimization, prediction, and analysis,
user_title: Open to Machine Learning, Data Science, Data Analyst roles
email: komal.ilyas9@gmail.com
#twitter_username: lorem_ipsum
github_username: komalilyas
Linkedin:  https://www.linkedin.com/in/komal-ilyas-045338116/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
